name: nix-cache-check
description: Check that the contents of a Nix cache or remote store is up-to-date
inputs:
  derivation:
    description: 'The derivation to build such as "github:holochain/holochain#devShells.x86_64-darwin.holonix"'
    required: true
  extra_build_args:
    description: 'Extra args to pass to `nix build`'
    required: false
    default: ''
  permit_build_derivations:
    description: "The comma-separated names of derivations which are permitted to be built rather than fetched from the cache"
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Check
      shell: bash
      run: |
        cargo install --locked --git https://github.com/holochain/nix-cache-check.git --tag v1
        nix-cache-check
      env:
        DERIVATION: ${{ inputs.derivation }}
        EXTRA_BUILD_ARG: ${{ inputs.extra_build_args }}
        PERMIT_BUILD_DERIVATIONS: ${{ inputs.permit_build_derivations }}

branding:
  icon: arrow-down-circle
  color: green
