name: Check

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo fmt --check
          cargo clippy --all-targets --all-features -- -D warnings
          cargo test --all-targets --all-features
  ci_pass:
    if: always()
    runs-on: ubuntu-latest
    needs: [ check ]
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

