name: Integration

on:
  push:
    branches: [ main ]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: cachix/install-nix-action@v22
        - uses: cachix/cachix-action@v12
          with:
            name: holochain-ci
        - name: Test
          uses: ./
          with:
            derivation: github:holochain/holochain#devShells.x86_64-darwin.holonix
            extra_build_args: --override-input versions github:holochain/holochain?dir=versions/0_2              
