name: Integration

on:
  push:
    tags: [ v1 ]
  workflow_dispatch: {}

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: cachix/install-nix-action@v30
        - uses: cachix/cachix-action@v15
          with:
            name: holochain-ci
        - name: Test
          uses: ./
          with:
            derivation: github:holochain/holonix?ref=main-0.4
